

export const fullProfessionList = [
    "Advogado",
    "Arquiteto",
    "Assistente Virtual",
    "Barbeiro",
    "Bombeiro",
    "Cabeleireiro",
    "Caminhoneiro",
    "Cantor",
    "Carpinteiro",
    "Catador de Reciclagem",
    "Chefe de Cozinha",
    "Contador",
    "Corretor de Imóveis",
    "Costureira",
    "Cozinheiro",
    "Cuidador de Idosos",
    "Designer de Interiores",
    "Designer Gráfico",
    "Diarista",
    "Dog Walker",
    "Dono de Frota / Aluguel de Veículo",
    "Eletricista",
    "Encanador",
    "Enfermeiro",
    "Engenheiro Civil",
    "Engenheiro de Software",
    "Entregador a Pé (Caminhada Remunerada)",
    "Esteticista",
    "Farmacêutico",
    "Fisioterapeuta",
    "Fotógrafo",
    "Fretes e Mudanças",
    "Garçom",
    "Gestor de Tráfego Pago",
    "Guia de Turismo",
    "Guincho",
    "Jardineiro",
    "Jornalista",
    "Jovem Aprendiz",
    "Lavador de Carros",
    "Maquiador",
    "Marceneiro",
    "Marido de Aluguel",
    "Massagista",
    "Mecânico",
    "Médico",
    "Montador de Móveis",
    "Motoboy",
    "Motorista de App",
    "Motorista Particular",
    "Músico",
    "Nutricionista",
    "Padeiro",
    "Paisagista",
    "Personal Organizer",
    "Personal Trainer",
    "Pet Sitter",
    "Pintor",
    "Pizzaiolo",
    "Podólogo",
    "Policial",
    "Porteiro",
    "Produtor de Eventos",
    "Professor Particular",
    "Programador",
    "Psicólogo",
    "Recepcionista",
    "Segurança",
    "Serralheiro",
    "Serviços Gerais",
    "Soldador",
    "Tatuador",
    "Taxista",
    "Técnico de Ar Condicionado",
    "Técnico de Celular",
    "Técnico de Enfermagem",
    "Técnico de Informática",
    "Técnico em Edificações",
    "Tradutor",
    "Vendedor",
    "Veterinário",
    "Vidraceiro",
    "Vigilante",
    "Web Designer"
];
